### ISSUE TITLE
example on how to use it with wireshark

### ISSUE THREAD

**Issue by lolorc** [andrewdodd/pyCCSniffer#6]
Hi,

could you provide some example on how to use it with wireshark please ?
or should I use another tool for that purpose ?
TIA

**Comment by andrewdodd** [comment]
Hey,

The original tool that I wrote is [ccsniffpiper](https://github.com/andrewdodd/ccsniffpiper), which was what I used to pipe captured frames into Wireshark.

I made this tool because I had a lot of custom payload information to dissect, and writing dissectors is a bit easier in Python than in the weird LUA/C stuff necessary for Wireshark.

So my recommendation would be:
 - If you just want to use out-of-the-box Wireshark, or if you already have custom Wireshark dissectors, use [ccsniffpiper](https://github.com/andrewdodd/ccsniffpiper)
 - If you have a bunch of custom dissectors to write, stick with this library

For more info, you can see my SO answer [here](https://stackoverflow.com/questions/41841230/wireshark-802-15-4-dissector-for-all-destinations-in-lua/45409041#45409041)

Good luck!
